AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  RawPrefix:
    Type: String
    Default: raw
  StructuredPrefix:
    Type: String
    Default: structured
  AnalyzedPrefix:
    Type: String
    Default: analyzed
  AwsRegionName:
    Type: String
    Default: us-east-1
  AlertEmail:
    Type: String
    Default: rodrigobdiass@gmail.com

Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME: !Ref ProductsBucket
        RAW_PREFIX: !Ref RawPrefix
        STRUCTURED_PREFIX: !Ref StructuredPrefix
        ANALYZED_PREFIX: !Ref AnalyzedPrefix
        AWS_REGION_NAME: !Ref AwsRegionName

Resources:
  # S3 Bucket for storing products data
  ProductsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.12
      CodeUri: lambdas/1.extractor/
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub '${ProductsBucket.Arn}/*'

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.12
      CodeUri: lambdas/2.processor/
      Timeout: 60
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub '${ProductsBucket.Arn}/*'

  AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.12
      CodeUri: lambdas/3.analyzer/
      Timeout: 180
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub '${ProductsBucket.Arn}/*'
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'

  ProductsStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: products-analyzer
      DefinitionUri: statemachine/definition.json
      DefinitionSubstitutions:
        ExtractorFunctionArn: !GetAtt ExtractorFunction.Arn
        ProcessorFunctionArn: !GetAtt ProcessorFunction.Arn
        AnalyzerFunctionArn: !GetAtt AnalyzerFunction.Arn
        FailuresTopicArn: !Ref FailuresTopic
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ExtractorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AnalyzerFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FailuresTopic.TopicName

  FailuresTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: product-failures-alert
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

Outputs:
  ProductsBucketName:
    Description: S3 bucket for products data
    Value: !Ref ProductsBucket
  StateMachineArn:
    Description: ARN of the Step Functions state machine
    Value: !Ref ProductsStateMachine
  FailuresTopicArn:
    Description: ARN of the SNS topic for failure alerts
    Value: !Ref FailuresTopic