AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Default: rodrigo-products-data
  RawPrefix:
    Type: String
    Default: rodrigo-products-data-raw
  StructuredPrefix:
    Type: String
    Default: rodrigo-products-data-structured
  AnalyzedPrefix:
    Type: String
    Default: rodrigo-products-data-analyzed
  AwsRegionName:
    Type: String
    Default: us-east-1
  AlertEmail:
    Type: String
    Default: rodrigobdiass@gmail.com

Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME: !Ref BucketName
        RAW_PREFIX: !Ref RawPrefix
        STRUCTURED_PREFIX: !Ref StructuredPrefix
        ANALYZED_PREFIX: !Ref AnalyzedPrefix
        AWS_REGION_NAME: !Ref AwsRegionName

Resources:
  ExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.12
      CodeUri: lambdas/1.extractor/
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: '*'

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.12
      CodeUri: lambdas/2.processor/
      Timeout: 60
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: '*'

  AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.12
      CodeUri: lambdas/3.analyzer/
      Timeout: 180
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
                - bedrock:*
              Resource: '*'

  ProductsStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: products-analyzer
      DefinitionUri: statemachine/definition.json
      DefinitionSubstitutions:
        ExtractorFunctionArn: !GetAtt ExtractorFunction.Arn
        ProcessorFunctionArn: !GetAtt ProcessorFunction.Arn
        AnalyzerFunctionArn: !GetAtt AnalyzerFunction.Arn
        FailuresTopicArn: !Ref FailuresTopic
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ExtractorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AnalyzerFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FailuresTopic.TopicName

  FailuresTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: product-failures-alert
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail